name = "oceanscape"
upload-to-group-id = 34310172

[[inputs]]

# For a syntax overview of Tarmac's globs, see:
# https://docs.rs/globset/0.4.4/globset/#syntax
glob = "assets/**/*.png"

# Tells Tarmac to generate links to our assets in src/assets.lua.
codegen = true
codegen-path = "src/assets.lua"
codegen-base-path = "assets"