name: Deploy to Testing Server

on:
  push:
    branches:
    - master

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4.0.2

    - name: Install Foreman
      uses: Roblox/setup-foreman@v1
      with:
        version: "^1.0.0"
        token: ${{ SECRETS.GITHUB_TOKEN }}

    - name: Build TS project
      run: |
        npm install
        npm run build

    - name: Build Roblox project
      run: rojo build -o oceanscape.rbxl

    - name: Deploy to Roblox
      run: rbxcloud experience publish --filename oceanscape.rbxl --place-id 17497948863 --universe-id 5988965500 --version-type published --api-key "${{ SECRETS.API_KEY }}"
